package co.syntropyhq.aqarat;

import co.syntropyhq.aqarat.dao.PropertyDao;
import co.syntropyhq.aqarat.dao.PropertySearch;
import co.syntropyhq.aqarat.model.DealType;
import co.syntropyhq.aqarat.model.PropertyStatus;
import co.syntropyhq.aqarat.util.Db;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.concurrent.Callable;
import org.junit.jupiter.api.Test;

/**
 * Measures the response times NFR-P1 and NFR-P3 are written against, so the report can
 * quote a number rather than assert a property.
 *
 * <p>Named so Surefire's default includes do not pick it up; it needs a seeded database.
 * Run explicitly:
 *
 * <pre>mvn test -Dtest=PerformanceProbe</pre>
 *
 * <p>Every figure is the median of {@value #SAMPLES} timed runs after {@value #WARMUP}
 * discarded warm-up runs, so JIT compilation and first-connection cost are excluded from
 * the reported figure and reported separately.
 */
class PerformanceProbe {

    private static final int WARMUP = 5;
    private static final int SAMPLES = 30;
    private static final Path OUTPUT = Path.of("docs", "evaluation", "performance.md");

    private final PropertyDao propertyDao = new PropertyDao();

    @Test
    void measure() throws Exception {
        Files.createDirectories(OUTPUT.getParent());
        List<Result> results = new ArrayList<>();

        // Cost of the very first connection, which builds the pool. Measured once,
        // before anything else has warmed it, or the figure is meaningless.
        long coldStart = timeOnce(() -> {
            try (Connection c = Db.get()) {
                return c.isValid(1);
            }
        });

        try (Connection connection = Db.get()) {
            results.add(measure("Pooled connection acquisition", () -> {
                try (Connection c = Db.get()) {
                    return c.isValid(1);
                }
            }));

            results.add(measure("Count all published listings", () ->
                propertyDao.count(connection, List.of(PropertyStatus.AVAILABLE), new PropertySearch())));

            results.add(measure("Unfiltered page of 50", () ->
                propertyDao.search(connection, List.of(PropertyStatus.AVAILABLE),
                    new PropertySearch(), 0, 50).size()));

            PropertySearch narrow = new PropertySearch();
            narrow.setDealType(DealType.RENT);
            narrow.setBedrooms(2);
            narrow.setHasParking(true);
            narrow.setIsFurnished(true);
            narrow.setMaxPrice(new BigDecimal("1200"));
            results.add(measure("Five-filter search, page of 50", () ->
                propertyDao.search(connection, List.of(PropertyStatus.AVAILABLE),
                    narrow, 0, 50).size()));

            results.add(measure("Every CLOSED property (the estimator's dataset)", () ->
                propertyDao.search(connection, List.of(PropertyStatus.CLOSED),
                    new PropertySearch(), 0, 5000).size()));

            results.add(measure("Full table scan of property", () -> {
                try (PreparedStatement s = connection.prepareStatement(
                        "SELECT COUNT(*) FROM property");
                     ResultSet rs = s.executeQuery()) {
                    rs.next();
                    return rs.getInt(1);
                }
            }));
        }

        write(results, coldStart);
    }

    private Result measure(String label, Callable<?> operation) throws Exception {
        for (int i = 0; i < WARMUP; i++) {
            operation.call();
        }
        long[] samples = new long[SAMPLES];
        for (int i = 0; i < SAMPLES; i++) {
            samples[i] = timeOnce(operation);
        }
        java.util.Arrays.sort(samples);
        return new Result(label,
            samples[SAMPLES / 2] / 1_000_000.0,
            samples[0] / 1_000_000.0,
            samples[(int) (SAMPLES * 0.95)] / 1_000_000.0);
    }

    private long timeOnce(Callable<?> operation) throws Exception {
        long start = System.nanoTime();
        operation.call();
        return System.nanoTime() - start;
    }

    private void write(List<Result> results, long coldStartNanos) throws IOException {
        try (PrintWriter out = new PrintWriter(Files.newBufferedWriter(OUTPUT))) {
            out.println("# Performance — measured output");
            out.println();
            out.println("Generated by `PerformanceProbe`. Reproduce with:");
            out.println();
            out.println("```");
            out.println("mvn test -Dtest=PerformanceProbe");
            out.println("```");
            out.println();
            out.printf("Median of %d timed runs after %d discarded warm-up runs.%n", SAMPLES, WARMUP);
            out.println("Single machine, local SQL Server, no contention. These are indicative");
            out.println("of the intended deployment and are not a benchmark of the database.");
            out.println();
            out.println("| Operation | Median (ms) | Fastest (ms) | 95th percentile (ms) |");
            out.println("|---|---|---|---|");
            for (Result r : results) {
                out.printf(Locale.ROOT, "| %s | %.2f | %.2f | %.2f |%n",
                    r.label(), r.median(), r.fastest(), r.p95());
            }
            out.println();
            out.printf(Locale.ROOT,
                "First connection of the session, which builds the pool: **%.1f ms**. "
                + "Every subsequent acquisition is the first row of the table above — this is "
                + "the cost pooling removes from each operation.%n",
                coldStartNanos / 1_000_000.0);
        }
        System.out.println("Wrote " + OUTPUT.toAbsolutePath());
        results.forEach(r -> System.out.printf(Locale.ROOT, "  %-48s %.2f ms%n", r.label(), r.median()));
    }

    private record Result(String label, double median, double fastest, double p95) { }
}
